services:
  - type: web
    name: vihanga-portfolio
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: CONTACT_EMAIL_PASS
        sync: false
    autoDeploy: true
